drop table if exists comments;
drop table if exists boards;
create table boards (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    content clob not null,
    created_at timestamp not null
);

